name: Build

on:
  workflow_dispatch: # Ручной запуск через интерфейс GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Загружает код из репозитория в среду выполнения GitHub Actions
    - name: Checkout code
      uses: actions/checkout@v4

    # Логинится в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Сборка и публикация Docker-образа
    - name: Build and push Docker image
      run: |
        docker build \
          --build-arg SECRET_KEY=${{ secrets.SECRET_KEY }} \
          --build-arg ALLOWED_HOSTS=${{ secrets.ALLOWED_HOSTS }} \
          --build-arg SQL_DATABASE=${{ secrets.SQL_DATABASE }} \
          --build-arg SQL_USER=${{ secrets.SQL_USER }} \
          --build-arg SQL_PASSWORD=${{ secrets.SQL_PASSWORD }} \
          --build-arg SQL_PORT=${{ secrets.SQL_PORT }} \
          --build-arg DATABASE=${{ secrets.DATABASE }} \
          --build-arg DJANGO_SUPERUSER_USERNAME=${{ secrets.DJANGO_SUPERUSER_USERNAME }} \
          --build-arg DJANGO_SUPERUSER_EMAIL=${{ secrets.DJANGO_SUPERUSER_EMAIL }} \
          --build-arg DJANGO_SUPERUSER_PASSWORD=${{ secrets.DJANGO_SUPERUSER_PASSWORD }} \
          -t vadongera/user-notes:latest .
        docker push vadongera/user-notes:latest
