name: Build

on:
  workflow_dispatch: # Ручной запуск через интерфейс GitHub Actions

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Загружает код из репозитория в среду выполнения GitHub Actions
    - name: Checkout code
      uses: actions/checkout@v3

    # Логинится в Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}


