name: Copy to Server

on:
  push:
    branches:
      - main  # Запускается при пуше в ветку main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H ${{ secrets.SERVER_IP }} >> ~/.ssh/known_hosts

    - name: Copy repository to server
      run: |
        rsync -avz --delete \
          --exclude='.git' \
          --exclude='.env' \
          --exclude='.env.example' \
          --exclude='.gitignore' \
          --exclude='docker-compose.db.yml' \
          --exclude='.github/' \
          ./ \
          ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:/home/${{ secrets.SERVER_USER }}/user-notes/

#    - name: Post-deploy actions
#      run: |
#        ssh ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} << 'EOF'
#          cd /home/${{ secrets.SERVER_USER }}/user-notes/
#          docker-compose down
#          docker-compose up -d --build
#        EOF
